### PR TITLE
Fix compilation issues in examples - Updated

### PR DESCRIPTION
**Pull request by joelpenov**

### CODE REVIEW

**Comment by ghiscoding** [comment]
Hey thanks again for the PR, it looks like you got most of the examples working and it's nice to see that. I got couple of questions
- are you friend with @speige @garnerdy? he started this fork with one of his coworker and I'm asking because I'm not using React myself and my knowledge is limited here but the code looks ok to me so far
- something I noted to @speige was that it reloads the entire page every time we change example and it shouldn't do that (it's a SPA, so it should just be a route change) and since I'm not a React developer, I don't know how to fix that myself, if you could fix it in a future PR that would be really great :)
- I see a few examples loading but are throwing errors in the console, so would you like to fix them in this PR or in future PR? I don't mind either way, I'm just asking what would be your preference. here's a demo of a console error when I go on Example 10 
```sh
react-dom.development.js?61bb:67 Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```

Let me know what are you preference, as I said I could merge the PR as it is and you could do future PRs or do you prefer to fix all of them in the same PR? It's up to you, I'm flexible, thanks again for the PR 😉

**Comment by ghiscoding** [comment]
@joelpenov I forgot to mention you, so I'm not sure if you've seen the message I left.

**Comment by joelpenov** [comment]
> ```shell
> Warning
> ```


First of all, I want to thank you for all the answers you posted in stackoverflow.com and the documentation/examples of Angular SlickGrid. I worked with the Angular version in a project with @speige and that ease my work a lot. 

1. I worked for @speige too. I also worked in my free time to finish this PR with the help of my friend @esmarlin09

2. I'm afraid I do not have enough time right now, but I will try to fix the reloading issue later.

3. Fixing the console errors seems to be an easy fix, so I will start by doing that.

4. If you agree we can merge this PR first, and when I have time later, I will be happy to continue contributing to this project.

**Comment by ghiscoding** [comment]
Sounds good, thanks for replying and let me know if you want me to release a new version. We could also wait until you have time to fix the other issues, it's up to you so just let me know, I'm flexible 😉 

have a nice day

**Pull request merged**
